name: Bundler

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bundle and commit
      run: |
        npm ci
        npm run build
        git checkout -b origin/gh-pages
        git add bundle.js
        git commit -m "[Action] npm run build"
        git push -u origin origin/gh-pages
