name: Bundler

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Bundle and commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm ci
        npm run build
        git add bundle.js
        git commit -m "[Action] npm run build"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
